version: '3'

services:

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - 9000:9000
    environment:
      - SONAR_EQ_BOOTSTRAP_CHECKS_DISABLE=true
  db:
    image: library/postgres:15-alpine
    container_name: spring-db
    environment:
      - POSTGRES_USER=${DB_URL}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  app:
    build: ./
    container_name: 'spring-actions'
    depends_on:
      - db
      - sonarqube
    ports:
      - 8080:8080

volumes:
  db-data:


