version: '3'

services:

  db:
    image: library/postgres:15-alpine
    container_name: spring-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  app:
    build: ./
    container_name: 'spring-actions'
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  db-data:

